Updating CONFIG_PROPERTIES_BLACKLIST_DEFAULT value
ryannedolan/kafka pull request #1
Opened 2019-07-02 07:41 UTC by arunmathew88

Some more configs which doesn't make sense to be replicated to target cluster.
throttled.replicas -> need not map to same broker ids in target
message.timestamp.difference.max.ms -> might cause message drops if not adjusted for replication delays
unclean.leader.election.enable -> one would prefer more consistency over availability on a backup replica.

2019-07-08 19:09 UTC, ryannedolan requested changes

2019-07-08 19:09 UTC, ryannedolan commented on connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorSourceConnector.java
> +        entry = (entry.permissionType() == AclPermissionType.ALLOW && entry.operation() == AclOperation.ALL)?
Don't re-assign to a value like this. Pretend everything is "final", even if it isn't.

Don't use the ternary operator for conditional logic like this. Prefer if-statements.

I'd do something like:

```
final AccessControlEntry entry;
if (...) {
   entry = ...
} else {
   entry = ...
}
```

2019-07-08 19:09 UTC, ryannedolan commented on connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorSourceConnector.java
> +            .filter(x -> !(x.entry().permissionType() == AclPermissionType.ALLOW && x.entry().operation() == AclOperation.WRITE))
IMO, this is complex enough to warrant a named method, similar to shouldReplicateTopic below. In-line lambdas like this should be absolutely trivial -- a method call, a bit of arithmetic, a comparison... this expression is just complex enough that I had to read it a couple times, which tells me a method name would be better here.

2019-07-08 19:09 UTC, ryannedolan commented on connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorSourceConnector.java
> +        entry = (entry.permissionType() == AclPermissionType.ALLOW && entry.operation() == AclOperation.ALL)?
You might consider extracting this as a separate method, e.g. targetAccessControlEntry().

2019-07-08 19:09 UTC, ryannedolan commented on connect/mirror/src/main/java/org/apache/kafka/connect/mirror/DefaultConfigPropertyFilter.java
> +    public static final String CONFIG_PROPERTIES_BLACKLIST_DEFAULT = "follower\\.replication\\.throttled\\.replicas, "
awesome thx

2019-07-17 20:49 UTC, arunmathew88 commented
Thanks for all the review comments @ryannedolan. I have made the changes as advised.

2019-07-17 21:16 UTC, ryannedolan approved these changes
looks good, thx!

2019-07-17 21:17 UTC, merged